### ISSUE TITLE
Failed to load function chuzitems:entity/effect/lockon_marker/summon

### ISSUE THREAD

**Issue by KisaragiEffective** [Chuzume/Chuzume-s-Items#1]
いつもお世話になっています。1.2.0を1.20.2のサーバーでロードしようとすると以下のようなエラーが発生してしまいます:

```
[16:42:35] [ServerMain/ERROR]: Failed to load function chuzitems:entity/effect/lockon_marker/summon
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 7: Expected double at position 20: ...m_display <--[HERE]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 7: Expected double at position 20: ...m_display <--[HERE]
        at net.minecraft.commands.CommandFunction.fromLines(CommandFunction.java:119) ~[?:?]
        at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:80) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

ご確認をお願いします:

https://github.com/Chuzume/Chuzume-s-Items/blob/1f832a369a3e01dbe10fc881622f33be7a12e0f4/data/chuzitems/functions/entity/effect/magic/summon.mcfunction#L8

**Comment by Chuzume** [comment]
バニラサーバー以外での動作は保証できず、またこのエラーもバニラのサーバーでは起きないと思うので、サーバーの環境を教えて頂けますか？

2023年12月22日(金) 16:49 Kisaragi ***@***.***>:
